#!/bin/bash

set -e

extract() {
	printf '==> Upgrading vendor firmware package...\n'
	asahi-fwupdate
}

case "$1" in
	configure)
		extract
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 0
	;;
esac

#DEBHELPER#

